[project]
name = "python312"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.basedpyright]
typeCheckingMode = "all"
