[project]
name = "hybridsyncasync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "xsync>=0.2.1",
]

[tool.basedpyright]
typeCheckingMode = "all"
